### ISSUE TITLE
404 Issue in exercise 5 developer edition

### ISSUE THREAD

**Issue by anushabc** [microsoft/MCW-Cloud-native-applications#214]
In Exercise 5, task 5,  step 9 encountered the error  404 Not Found nginx/1.19.1. However, I was able to perform with these commands

- helm repo add stable https://charts.helm.sh/stable

- helm repo update

- helm install nginx stable/nginx-ingress

But in task 6, step 9 when browsing from Traffic manager DNS it shows default backend - 404. 

We have an active environment, can provide it if needed for checking the issue

**Comment by sumitmalik51** [comment]
Hello @timahenning,
did you get any chance to look on the above issue? we are having daily events for this workshops under AIW event.

**Comment by timahenning** [comment]
Hi @sumitmalik51, I will try to have someone look at it today or tomorrow.

Tim

**Comment by crpietschmann** [comment]
I committed a fix for the change in official Helm repo url. The Google hosted one was deprecated recently. This should fix the issue.

**Comment by sumitmalik51** [comment]
Thanks for the update @crpietschmann, Will test out and reopen the issue if needed. Thanks

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved.

**Comment by anushabc** [comment]
Hi @crpietschmann, still facing the same issue in Exercise 5 can you please check on this.

![image](https://user-images.githubusercontent.com/66515706/104732945-f6dd2900-5763-11eb-8f79-e94e3a50a484.png)

**Comment by rob-mckenna** [comment]
Also still facing the same issue at Exercise 5.  The fix implemented is in step 2 and states "Note: If you get a "no repositories found." error..." then execute.  So it appears not everyone would need this step.  I did not need to run the updated command based on this as I did not get the "no repositories found" error.

It's also not clear how the updated command will fix the 404 Not Found issue.
Can you provide guidance on how to remediate if you've already executed Exercise 5?
Or are there additional steps that need to be taken here?

**Comment by timahenning** [comment]
@rob-mckenna Hi Rob, I have reached out to Chris to speed up an answer.

**Comment by akn9050** [comment]
Hi, any update on the issue.

**Comment by crpietschmann** [comment]
I am running through the lab steps to dig further into this 404 error you're seeing.

**Comment by akn9050** [comment]
Hi @DawnmarieDesJardins , @crpietschmann any update on this, customers are reporting issues with this. Please provide any ETA to fix this. Also, is there any workaround for this issue?

**Comment by crpietschmann** [comment]
I am actively working to figure out a fix for this.

**Comment by crpietschmann** [comment]
@DawnmarieDesJardins @timahenning  I was able to figure out a configuration change that works to fix the 404 errors. It's included in PR #229. :)

**Comment by DawnmarieDesJardins** [comment]
@sumitmalik51 @akn9050 - Please test with the latest PR merge and let me know if I can close as resolved.

**Comment by akn9050** [comment]
Thanks @Chris and @DawnmarieDesJardins, we will test and update accordingly

**Comment by anushabc** [comment]
HI @crpietschmann,  I am still getting this page in the Exercise5 Task 6 step 11. We have an active environment, can provide it if needed

![image](https://user-images.githubusercontent.com/66515706/106666274-64df7800-65cd-11eb-921d-81f9cbeb335a.png)

**Comment by DawnmarieDesJardins** [comment]
@crpietschmann @timahenning 
Hello,  
Any movement on this one?  Spektra is still getting the error.

**Comment by crpietschmann** [comment]
@DawnmarieDesJardins I never got access to their environment so I could help troubleshoot what they were seeing.
@timahenning

**Comment by DawnmarieDesJardins** [comment]
@anushabc @akn9050 
Hello!  Please provide @crpietschmann access to your environment to troubleshoot.  He's not able to reproduce your error when he goes through the lab.  Thank you!

**Comment by crpietschmann** [comment]
@anushabc @akn9050 The environment you had provided me to troubleshoot had an app insights error in the code deployed, for which I didn't have access to the GitHub repo for, and was not to the point for the 404 error you are seeing to be exhibited. I replied to the email about this, but never got a response.

Is this still an issue?

**Comment by crpietschmann** [comment]
FYI (above) @timahenning

**Comment by anushabc** [comment]
We tested the lab recently and we didn't face this issue anymore.
