### ISSUE TITLE
Azure DevOps repos and Linux require SSH. HTTPS does not work.

### ISSUE THREAD

**Issue by RonnyA** [microsoft/MCW-Cloud-native-applications#59]
I spent the last 2-3 hours trying to get Git to authenticate and remember its setting with Azure DevOps repos for this lab. 

I tried every trick in the book and had some random things to work (ie "git clone" worked using a personal access token instead of password, but trying a "git pull" immediately after made git ask for username and passord AGAIN and whatever I type it will not do anything then say "Fatal : Authentication failed for https://dev.azure.com/...")

I checked with others and they where clear that Linux with Azure DevOps - DO NOT USE HTTPS, but use SSH as described here https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops

I think this should be integrated into the documentation.

**Comment by DawnmarieDesJardins** [comment]
Thanks RonnyA.  I'm labeling this issue as an enhancement so our authors have it for the next update.

**Comment by RonnyA** [comment]
I just learned that the reason why my HTTPS didnt work was that my alias and my organisation name was identical (ie DevOps organization=ronnyha and alias=ronnyha) then authentication did always fail. If I created an alias that was different from my organization (ie alias = ronnyha1) then I could use https.
However, i would probably still recommend using SSH because of the added security benefits.

**Comment by jamesrcounts** [comment]
I believe HTTS auth issues have been resolved in #63

**Comment by benc-uk** [comment]
There is also a  bug in the Git Credential Manager which can trip this step up 
https://github.com/Microsoft/Git-Credential-Manager-for-Mac-and-Linux/issues/90

Which means the steps as described didn't work for me

The workaround I found was to use the legacy URLs for the git remote
e.g. this Git URL
```
git remote add origin https://dev.azure.com/myorg/fabmedical/_git/content-api
```

Should be changed to, the older visual studio URL, which still works and works with Git-Credential-Manager
```
git remote add origin https://myorg.visualstudio.com/fabmedical/_git/content-api`
```

**Comment by jamesrcounts** [comment]
@benc-uk Are you suggesting that we should add a note about this workaround?  We're you running on the full setup as described in "Before the hands-on-lab" when you ran into this error?

**Comment by DawnmarieDesJardins** [comment]
Closing issue.  Please reopen if problem still exists.
Thank you

**Comment by PriyankaGupta05** [comment]
> There is also a bug in the Git Credential Manager which can trip this step up
> [microsoft/Git-Credential-Manager-for-Mac-and-Linux#90](https://github.com/microsoft/Git-Credential-Manager-for-Mac-and-Linux/issues/90)
> 
> Which means the steps as described didn't work for me
> 
> The workaround I found was to use the legacy URLs for the git remote
> e.g. this Git URL
> 
> ```
> git remote add origin https://dev.azure.com/myorg/fabmedical/_git/content-api
> ```
> 
> Should be changed to, the older visual studio URL, which still works and works with Git-Credential-Manager
> 
> ```
> git remote add origin https://myorg.visualstudio.com/fabmedical/_git/content-api`
> ```

HTTPS still does not work for me.
I cannot git push anything back to my Azure repo without giving credentials in my pipeline.

**Comment by DawnmarieDesJardins** [comment]
Reopening issue with new information received.

**Comment by vraposo** [comment]
@PriyankaGupta05 is it possible to provide some more information on which section of the document this issue happens? Is it in the *Before the HOL* document or in one of the *HOL* documents?

Just to double-check, I'm assuming you are using the Azure Cloud Shell like mentioned in the documents, correct?

**Comment by PriyankaGupta05** [comment]
@vraposo  Hey , I am used 2 types of Microsoft hosted agents [Ubuntu 18 LTS & MacOS 10.14].
Same error used to happen in them.
In my case , Azure Pipeline was not able to :: git push :: to Azure repos being in the same Azure organisation [Both repo & pipelines].
I tried to give git credentials in a Bash task :: git config global xx .
Nothing worked.
Finally i have to do Generate Git credentials in Azure Repos --> Clone URL option.
Those git credentials generated , i used in azure pipeline Bash task.
This much has to done to git push from Azure pipelines to Azure repos.

.......

What I wanted to do is use 1 generic User git credential which is "Contributor" in all my different organisation & projects inside it to do git push.

That is very far from the things i just found as work around.

Can you please help with it.

**Comment by vraposo** [comment]
It looks like you might be deviating from the lab instructions or it could be I do not have enough lab context of where you are having troubles.

We will try to assist you if there are easy to understand requests with clear references to which document and section it relates to. Unfortunately, we cannot debug unique environments. There are too many variations.

Would you please be able to provide screenshots blurring sensitive information so that I can provide assistance?

Thanks

**Comment by PriyankaGupta05** [comment]
![build](https://user-images.githubusercontent.com/20393916/73346936-07606f00-4287-11ea-9a87-570469fc78ec.png) This is my yaml file which i made it so simple for testing.
![yaml](https://user-images.githubusercontent.com/20393916/73346937-07f90580-4287-11ea-8a90-8b876445e3d8.png)
this is build output.

I did all possible permissions enabled . which were needed to do for this "git push" command to work and push to Azure Repos in same organisation.

But nothing worked..

Should I provide anything else , please let me know.

**Comment by timahenning** [comment]
@PriyankaGupta05 Is there a specific part of the lab you are referring to?  Please reply back with the exact exercise and step.

Thanks,

Tim

**Comment by PriyankaGupta05** [comment]
Hello everyone,

I tried this in  my company for 4 organisations where i want to use only 1 generic user credentials to access Azure Repos from Azure Pipelines. 

I just want to push some information back to azure repos , which is getting generated while building in Azure pipelines USING only MY Credentials.

 I **DO NOT** want all users to use their credentials[OAuth] for the git push to Azure Repos from pipelines.

This is my requirement for the Azure Devops Project --> Repos and Pipelines.

**Comment by vraposo** [comment]
@PriyankaGupta05 it looks like you might be deviating from the lab instructions (please correct me if I am wrong here), because there is no place in any of the lab documentation files that implies pushing code from an Azure Pipeline to an Azure DevOps repository.

This issue tracking relates with the _MCW-Cloud-native-applications_ lab, so anything that doesn't relate with the lab itself does not belong here.

It seems that the issue you're presenting is related with the BashV3 pipeline script (https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/BashV3), so probably the best place to get help on the task behavior is in the **Tasks for Azure Pipelines** repo located at https://github.com/microsoft/azure-pipelines-tasks

**Comment by timahenning** [comment]
@PriyankaGupta05 Is there a specific part of the lab you are referring to? Please reply back with the exact exercise, task, and step.  We can only provide support for the lab exercises.  The authors cannot duplicate your issue in the lab at this time.  All other support will need to be handled by Microsoft Support.  Without specific lab references and errors we can duplicate, we will have to close the issue.

Thank you for your understanding,

Tim

**Comment by PriyankaGupta05** [comment]
Yeah its not in the lab instructions and its was just my company's requirement. 
I raised this question due to similar issue being talked about.

**Comment by timahenning** [comment]
Thank you for the follow-up.
